version: '3'  # Use version 3 or higher for docker-compose

services:
  homeworkmngt_app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: homeworkmngt_app
    ports:
      - '8080:8080'
    #depends_on:
    #  - homeworkmngt_db
    environment:
      #- SPRING_DATASOURCE_URL=jdbc:postgresql://homeworkmngt_db:5432/homework-management
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/homework-management
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=P@nVi2023!
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - LOCAL.SOURCE.DIRECTORY=/sftp/eKidz/Homeworks/IN/
      - LOCAL.SUCCESS.DESTINATION.DIRECTORY=/sftp/eKidz/Homeworks/SUCCESS/
      - LOCAL.ERROR.DESTINATION.DIRECTORY=/sftp/eKidz/Homeworks/ERROR/
    volumes:
      - "C:/SFTP/eKidz/Homeworks/IN:/sftp/eKidz/Homeworks/IN"
      - "C:/SFTP/eKidz/Homeworks/SUCCESS:/sftp/eKidz/Homeworks/SUCCESS"
      - "C:/SFTP/eKidz/Homeworks/ERROR:/sftp/eKidz/Homeworks/ERROR"

#  homeworkmngt_db:
#    image: 'postgres:13.1-alpine'
#    restart: always
#    container_name: homeworkmngt_db
#    ports:
#      - '5432:5432'
#    environment:
#      - POSTGRES_PASSWORD=password
#      - POSTGRES_USER=postgres
#      - POSTGRES_DB=homework-management
