@host = http://localhost:5199
POST {{host}}/users?api-version=1.0
Accept: application/json
Content-Type: application/json; charset=utf-8

{
    "userName": "LeonidPetrov",
    "email": "ungerfall@gmail.com",
    "roles": ["Administrator"]
}

###
GET {{host}}/users?api-version=1.0
Accept: application/json

###
DELETE {{host}}/users/e7bdd26c-0545-462f-539c-08dcb4eacf0f?api-version=1.0

###
PATCH {{host}}/users/a5066135-078b-453a-93d9-08dcb67d5483?api-version=1.0
Accept: application/json
Content-Type: application/json; charset=utf-8

{
    "userName": "LeonidPetrovNewNameAgain"
}
