@host = http://localhost:5199
POST {{host}}/users?api-version=1.0
Accept: application/json
Content-Type: application/json; charset=utf-8

{
    "userName": "LeonidPetrov",
    "email": "ungerfall@gmail.com"
}

###
GET {{host}}/users?api-version=1.0
Accept: application/json

###
