version: '3'

services:
  java_app:
    build:
      context: ./homework-checker-daemon
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgresql

  dotnet_app:
    build:
      context: ./chatbot
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgresql

  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

